### ISSUE TITLE
Pre-printed orange payment slip : only print account number in the code line

### ISSUE THREAD

**Issue by sdespont** [ravage84/SwissPaymentSlipPdf#6]
Hello,

I am trying your project and I have a question regarding the "Orange Payment Slip".
Sometimes, the account number is already pre-printed on the payment slip. Therefore, I don't want to print the data a second time.

Is there a way to set the project to only print the account number in the code line and not in the account ?

Best regards

**Comment by ravage84** [comment]
Hello, yes this is possible.

Normally fill the [OrangePaymentSlipData](https://github.com/ravage84/SwissPaymentSlip/blob/0.12.0/src/OrangePaymentSlipData.php) object will all necessary fields __including__ the account number, because the account number is also calculated into the code line (right bottom) .

But then, you disable the display of the account number fields on the left and the right on the payment slip by setting ``setWithAccountNumber`` in [PaymentSlip](https://github.com/ravage84/SwissPaymentSlip/blob/0.12.0/src/PaymentSlipData.php#L234-L244) to ``false``.

Similar example:
https://github.com/ravage84/SwissPaymentSlip/blob/0.12.0/examples/OrangePaymentSlipData_Advanced_Usage.php#L29-L47

**Comment by sdespont** [comment]
Thank you for your answer. Unfortunately, disabling the account number with setWithAccountNumber doesn't permit to generate the code line (code line is void)?! I would like to print the account number in the code line, but not in the payment slip above the amount field because it is already pre-printed.

Here is my code :

        $paymentSlipData = new OrangePaymentSlipData();

        // Fill the data container with your data
        $paymentSlipData->setBankData($bankAddress1, $bankAddress2);
        $paymentSlipData->setAccountNumber($account);
        $paymentSlipData->setRecipientData($recipientName, $recipientAddressLine1, $recipientAddressLine2, $recipientAddressLine3);
        $paymentSlipData->setPayerData($contact->getDisplayName(), $contact->getAddressLine1(), $contact->getAddressLine2());
        $paymentSlipData->setAmount($entity->getAmount());
        $paymentSlipData->setReferenceNumber($refNumber);    
        $paymentSlipData->setBankingCustomerId($bankingCustomerId);  

        $paymentSlipData->setWithAccountNumber(false);

        // Create a payment slip object, pass in the prepared data container
        $paymentSlip = new OrangePaymentSlip($paymentSlipData, 0, 191);
        $paymentSlip->setSlipBackground('transparent');

        // Since we currently don't have a OCRB font for TCPDF, we set it to one we certainly have
        $paymentSlip->setCodeLineAttr(null, null, null, null, null, 'ocrb10');

        // Create an instance of the TCPDF implementation, can be used for TCPDF, too
        $paymentSlipTcpdf = new PaymentSlipTcpdf($tcPdf);

        // "Print" the slip with its elements according to their attributes
        $paymentSlipTcpdf->createPaymentSlip($paymentSlip);

**Comment by ravage84** [comment]
Sorry, I gave you the wrong method, use ``setDisplayAccount()`` an set it to ``false``.
https://github.com/ravage84/SwissPaymentSlip/blob/0.12.0/src/PaymentSlip.php#L1217-L1229

Need more :coffee:

**Comment by ravage84** [comment]
Also, you need to set this on the ``PaymentSlip`` but not the ``PaymentSlipData`` object.

```` php
// Wrong
$paymentSlipData = new OrangePaymentSlipData();
$paymentSlipData->setWithAccountNumber(false);

// Correct
$paymentSlipData = new OrangePaymentSlipData();
$paymentSlip = new OrangePaymentSlip($paymentSlipData);
$paymentSlip->setDisplayAccount(false);
````

Please read the example thoroughly.
This library is very modular and because of this the functionality is split into various classes (for god reason).
For further questions, please contact me through my email.
Thanks.

**Comment by sdespont** [comment]
Thank you, it is working.
