### ISSUE TITLE
Drop support for old-fashioned red payment slip 

### ISSUE THREAD

**Issue by D4rkMindz** [ravage84/SwissPaymentSlipPdf#9]
The red payment slip is not required anymore. Consider dropping its support.

**Comment by ravage84** [comment]
I'm not going to implement or action this, anymore, as this package has become obsolete due to the introduction of the [Swiss QR code payment slip](https://de.wikipedia.org/wiki/QR-Rechnung) and the discontinuation of the old ESR.

One can use https://github.com/sprain/php-swiss-qr-bill for the new Swiss QR  bill.
